[package]
name = "vulkano-kit"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.34.0"
thiserror = "2.0.11"

[profile.dev]
opt-level = 1 
incremental = true
debug = 1
codegen-units = 16


