[package]
name = "vulkano-kit"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.35.1"
thiserror = "2.0.11"

[profile.dev]
opt-level = 1 
incremental = true
debug = 1
codegen-units = 16

[workspace]
members = ["playground"]
